#!/data/data/com.termux/files/usr/bin/bash

c1="\e[1;38;2;0;200;118m"
c2='\e[0;38;2;220;255;255m'
c3='\e[0m'
slp=$"sleep 0.03"

progress() {
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━━━━━${c3}              \r"
$slp
printf "${c1}━${c2}━━━━━━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━${c2}━━━━━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━${c2}━━━━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━━${c2}━━━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━━━${c2}━━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━━━━${c2}━━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━━━━━${c2}━━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c1}━━━━━━━━${c2}━━━━━━━━━━━━━━━━━${c3}         \r"
$slp
printf "${c2}━${c1}━━━━━━━━${c2}━━━━━━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━${c1}━━━━━━━━${c2}━━━━━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━${c1}━━━━━━━━${c2}━━━━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━${c1}━━━━━━━━${c2}━━━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━${c1}━━━━━━━━${c2}━━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━${c1}━━━━━━━━${c2}━━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━${c1}━━━━━━━━${c2}━━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━${c1}━━━━━━━━${c2}━━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━${c1}━━━━━━━━${c2}━━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━${c1}━━━━━━━━${c2}━━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━${c1}━━━━━━━━${c2}━━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━${c1}━━━━━━━━${c2}━━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━${c1}━━━━━━━━${c2}━━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━━${c1}━━━━━━━━${c2}━━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━${c1}━━━━━━━━${c2}━━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━${c1}━━━━━━━━${c2}━${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━${c1}━━━━━━━━${c2}${c3}    \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━${c1}━━━━━━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━${c1}━━━━━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━${c1}━━━━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━${c1}━━━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━━${c1}━━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━━━${c1}━━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━━━━${c1}━${c3}         \r"
$slp
printf "${c2}━━━━━━━━━━━━━━━━━━━━━━━━━${c1}${c3}         \r"
$slp
}

HIDE(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}
#C1="\e[92m"
#C2="\e[0m"

spinner() {
local pid=$!
local delay=0.0350

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
for progressbar in progress
do
	HIDE
        ${progressbar[@]} #printf $((progressbar))
	sleep $delay
done
done
NORM
printf "Complete ...!                           \n"
}

( sleep 5) &> /dev/null & spinner

